created_at: '2025-05-16 04:07:48'
dataset_name: gym
model_name: CatBoost
parameters:
  depth: '6'
  iterations: '100'
  l2_leaf_reg: '3'
  learning_rate: '0.1'
  loss_function: RMSE
  random_state: '42'
  verbose: 'False'
target_column: BMI
